apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple
  namespace: observability
spec: 
  ingress:
    enabled: false
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.62.0
    options:
      log-level: debug
      query:
        base-path: /jaeger
      # collector:
      #   otlp:
      #     enabled: true
      prometheus:
        server-url: "http://prometheus-service.monitoring.cluster.svc.local:9090"
    metricsStorage:
      type: prometheus
  storage:
    options:
      memory:
        max-traces: 100000
