apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    gitops.operator.app_repository: git@github.com:kainlite/gitops-operator.git
    gitops.operator.deployment_path: app/00-deployment.yaml
    gitops.operator.enabled: 'true'
    gitops.operator.image_name: kainlite/gitops-operator
    gitops.operator.manifest_repository: git@github.com:kainlite/gitops-operator-manifests.git
    gitops.operator.namespace: gitops-operator
    gitops.operator.notifications_secret_name: webhook-secret
    gitops.operator.notifications_secret_namespace: gitops-operator
    gitops.operator.ssh_key_name: ssh-key
    gitops.operator.ssh_key_namespace: gitops-operator
  labels:
    app: gitops-operator
  name: gitops-operator
  namespace: gitops-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator
  template:
    metadata:
      labels:
        app: gitops-operator
    spec:
      containers:
      - env:
        - name: RUST_LOG
          value: info
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://simple-collector-headless.observability.svc:4317
        image: kainlite/gitops-operator:71c0403928a20617152532574b23fd4ff61a00b9
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: http
          periodSeconds: 15
        name: gitops-operator
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /reconcile
            port: http
          initialDelaySeconds: 3
          periodSeconds: 300
          timeoutSeconds: 60
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
      securityContext:
        fsGroup: 65532
        runAsGroup: 65532
        runAsUser: 65532
      serviceAccountName: gitops-operator
