# Main deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator
  namespace: default
  labels:
    app: gitops-operator
  annotations: 
    gitops.operator.enabled: "true"
    gitops.operator.secret_name: "dockerhub"
    gitops.operator.secret_namespace: "default"
    gitops.operator.namespace: "default"
    gitops.operator.app_repository: "git@github.com:kainlite/gitops-operator.git"
    gitops.operator.manifest_repository: "git@github.com:kainlite/gitops-operator-manifests.git"
    gitops.operator.image_name: "kainlite/gitops-operator"
    gitops.operator.deployment_path: "app/deployment.yaml"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-operator
  template:
    metadata:
      labels:
        app: gitops-operator
    spec:
      serviceAccountName: gitops-operator
      containers:
      - name: gitops-operator
        image: kainlite/gitops-operator:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /reconcile
            port: http
          initialDelaySeconds: 60
          periodSeconds: 120
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 5
          periodSeconds: 15
