# Scoped service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-operator
  namespace: default
automountServiceAccountToken: true

---
# Access for the service account (cluster scoped list)
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-operator
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - watch
    - list

---
# Binding the role to the account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-operator
subjects:
- kind: ServiceAccount
  name: gitops-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: gitops-operator
  apiGroup: rbac.authorization.k8s.io
